# Namespace of controller_manager
controller_manager_ns: controller_manager
# List of all controllers
controller_list:
  - name: um/um_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
